### ISSUE TITLE
Trip page - clear map when trip is changed

### ISSUE THREAD

**Issue by marilynfletcher** [MAPC/bostonparks#82]
Christian -- Is this something you can look at? Tyrel took a quick shot at it, but wondered if you knew the code better.

**Comment by cspanring** [comment]
it's actually very easy to implement, as explained here: https://github.com/MAPC/bostonparks/commit/3c5bbecea791254c53989198f7f8db0a73230878#commitcomment-1422162

---

in order to remove map features you can track them in the overlays list  (https://github.com/MAPC/bostonparks/blob/develop/parkmap/static/parkmap/js/parkmap.js#L8 and https://github.com/MAPC/bostonparks/blob/develop/parkmap/static/parkmap/js/parkmap.js#L377) and then call clearmap() (https://github.com/MAPC/bostonparks/blob/develop/parkmap/static/parkmap/js/parkmap.js#L409) whenever you want to empty the map.

```
// track what's on the map
// works with any overlay object: marker, polyline, polygon
bp.overlays.push(mymarker);

// empty map
bp.clearmap();
```

**Comment by tyrelsouza** [comment]
I don't know what in my bp.generate_trip_obj. Would be an overlay, I use the bp.clearmap(), but I'm not sure if the way that I'm using the directions display touches any overlay. Line 625 is where I call it.

**Comment by cspanring** [comment]
`bp.clearmap()` removes all overlay objects (markers, lines, polygons) that are listed in `bp.overlays`. without knowing the Google Directions response object too well, I assume the overlays are somewhere in `directionsDisplay` https://github.com/MAPC/bostonparks/blob/develop/parkmap/static/parkmap/js/parkmap.js#L658

I'll look into this today...
